openapi: 3.0.0
info:
  title: Booking System API
  description: API for managing bookings for a service.
  version: "1.0.0"
servers:
  - url: https://api.bookingsystem.com/v1

paths:
  /bookings:
    get:
      summary: List all bookings
      operationId: listBookings
      tags:
        - bookings
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingList'

    post:
      summary: Create a new booking
      operationId: createBooking
      tags:
        - bookings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created

  /bookings/{bookingId}:
    get:
      summary: Get a booking by ID
      operationId: getBookingById
      tags:
        - bookings
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found

components:
  schemas:
    Booking:
      type: object
      required:
        - id
        - userId
        - serviceId
        - dateTime
      properties:
        id:
          type: string
        userId:
          type: string
        serviceId:
          type: string
        dateTime:
          type: string
          format: date-time

    BookingList:
      type: object
      properties:
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'

